
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUUtzna36A0AieHrMN8NaNWK2A8gwatQY',
    appId: '1:613207651681:web:70eb0f61e5d5977bf94120',
    messagingSenderId: '613207651681',
    projectId: 'ff-win-flutter-d5761',
    authDomain: 'ff-win-flutter-d5761.firebaseapp.com',
    storageBucket: 'ff-win-flutter-d5761.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM3B2GG_YJO_jZnEUWxRRHD-Gu2CoHDdY',
    appId: '1:613207651681:android:59c720e7b699e2dff94120',
    messagingSenderId: '613207651681',
    projectId: 'ff-win-flutter-d5761',
    storageBucket: 'ff-win-flutter-d5761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjCTXDorf33NyusClbtuCozmJXtXM5wQ',
    appId: '1:613207651681:ios:673dc75233187da2f94120',
    messagingSenderId: '613207651681',
    projectId: 'ff-win-flutter-d5761',
    storageBucket: 'ff-win-flutter-d5761.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjCTXDorf33NyusClbtuCozmJXtXM5wQ',
    appId: '1:613207651681:ios:673dc75233187da2f94120',
    messagingSenderId: '613207651681',
    projectId: 'ff-win-flutter-d5761',
    storageBucket: 'ff-win-flutter-d5761.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
